# ===================================================================
# Spring Boot configuration for the "dev" profile.
#
# 本配置会覆盖application.yml文件中的配置.
# ===================================================================

# ===================================================================
# 标准的Spring Boot属性.
# 完整参考资料可在以下地址查阅:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

##服务器配置
server:
  port: 1996    #端口号
  #context-path: /     #基础路径

#debug: true
#  logging:
#    level:
#      com.cy.mapper: debug    #打印sql语句

##框架集成配置
spring:
  devtools:
    restart:
      enabled: true  #设置开启热部署
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB   #最大文件大小
      max-request-size: 10MB    #最大请求大小
  datasource:
    #type: com.zaxxer.hikari.HikariDataSource #SpringBoot2.x版本默认使用HikariCP这个数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:65236/annotation_translation?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    hikari:
      connection-timeout: 20000
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 300000
      max-lifetime: 1200000
      auto-commit: true
  jmx:
    default-domain: Annotation_translation
  redis:
    database: 0  #Redis数据库索引（默认为0）
    host: 127.0.0.1      #Redis服务器地址
    port: 6379             #Redis服务器连接端口
    password:               #Redis服务器密码（默认为空）
    pool:
      max-active: 100    #连接池最大连接数（使用负值表示没有限制）
      max-wait: -1      #连接池最大阻塞等待时间（使用负值表示没有限制）
      max-idle: 50      #连接池中的最大空闲连接
      min-idle: 10       #连接池中的最小空闲连接
    timeout: 5000          #连接超时时间（毫秒）
    expiry:
      loanStatistic: 600 #订单统计结果缓存时间:10分钟
  boot:
    admin:
      client:
        url: http://127.0.0.1:8081 #服务端注册路径
        username: admin
        password: 123456
        instance:
          name: Annotation_translation
          service-base-url: http://127.0.0.1:8086 #客户端基础路径
          #metadata:
          #  user.name: admin
          #  user.password: 123456


  jackson: #设置时区
    time-zone: GMT+8

mapper:
  mappers:
    - tk.mybatis.mapper.common.Mapper
  notEmpty: true

mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.cy.domain
  config-location: classpath:mybatis-config.xml

logging:
  file: ${cy.logger.path}/TimeAttendance.log

management:
  endpoints:
    web:
      exposure:
        include: "*" #暴露所有监控端点，这个配置不安全
  endpoint:
    health:
      show-details: always

# ===================================================================
# 自定义配置
# ===================================================================
cy:
  cross-origin: # 跨域配置
    access-control:
      allow-headers: authorization, content-type, sign # 允许跨域访问的请求头
      allow-origin: '*' # 允许跨域访问的地址
      max-age: 1728000 # 跨域访问配置的缓存时间(s)
  file: # 文件相关配置
    path: D:/Annotation_translation/upload # 文件上传路径
  logger: # 日志相关配置
    path: C:/Annotation_translation/log
  package: